### ISSUE TITLE
Specify full address for rewrite destination?

### ISSUE THREAD

**Issue by simonedavico** [zeit/serve-handler#28]
I am launching `serve` with a `serve.json` file. I have a rewrite like this:

```
{
  "source": "/foo/api/:rest",
  "destination": "http:/xxx.xx.x.xx:8080/foo/api/:rest"
}
```

But this causes an error when I launch `serve`:

```
(node:14574) UnhandledPromiseRejectionWarning: TypeError: Expected "8080" to be a string
    at /Users/sdavico/Development/installer/webapp/node_modules/serve-handler/node_modules/path-to-regexp/index.js:194:13
    at toTarget (/Users/sdavico/Development/installer/webapp/node_modules/serve-handler/src/index.js:68:9)
    at applyRewrites (/Users/sdavico/Development/installer/webapp/node_modules/serve-handler/src/index.js:85:18)
    at module.exports (/Users/sdavico/Development/installer/webapp/node_modules/serve-handler/src/index.js:547:24)
    at Server.http.createServer (/Users/sdavico/Development/installer/webapp/node_modules/serve/bin/serve.js:147:58)
    at Server.emit (events.js:160:13)
    at parserOnIncoming (_http_server.js:618:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

**Comment by thisguychris** [comment]
@simonedavico rewrites are for rewriting to internal paths, and doesn't support external URLs if that's what you were aiming?

**Comment by simonedavico** [comment]
Yes, I was indeed aiming for the ability to proxy my API calls to an external address. In the end I had to switch to [light-server](https://github.com/txchen/light-server), which supports this option. It would be nice too see this in `serve-handler` as well, if it's not out of scope w.r.t the purpose of the package.
